export default {
  "/education.html": {
    title: "Обучающий раздел",
    quizPageTitle: "3 - 7 лет",
    quizBackHref: "/index.html",
    quizBackText: "Назад",
    educationRatingTag: "Статистика",
    educationSectionsDone: "10",
    educationSectionsTotal: "11",
    educationRatingTitle: "Спасибо за вашу оценку!",
    educationRatingDescription:
      "Это поможет нам стать лучше и сделать онлайн-платформу полезнее",
    educationRatingInitial: 10,
    educationCards: [
      {
        typeLabel: "Видеолекция",
        durationLabel: "3 минуты",
        title: "Правила индивидуальной гигиены",
        image: "/images/education-card/1.webp",
        imageClass: "education-card__image--brush",
        imageWidth: "1082",
        imageHeight: "1082",
        href: "#",
        ctaLabel: "Открыть тему «Правила индивидуальной гигиены»",
      },
      {
        typeLabel: "Видеолекция",
        durationLabel: "3 минуты",
        title: "Красивые зубки",
        subtitle:
          "Игнатьева Лиля Александровна, КМН<br>Ассистент кафедры стоматологии<br>детского возраста",
        image: "/images/education-card/2.webp",
        imageClass: "education-card__image--girl",
        imageWidth: "470",
        imageHeight: "664",
        href: "#",
        ctaLabel: "Открыть тему «Красивые зубки»",
      },
      {
        typeLabel: "Видеолекция",
        durationLabel: "3 минуты",
        title: "Как чистить зубы правильно",
        image: "/images/education-card/1.webp",
        imageClass: "education-card__image--brush",
        imageWidth: "1082",
        imageHeight: "1082",
        href: "#",
        ctaLabel: "Открыть тему «Как чистить зубы правильно»",
      },
      {
        typeLabel: "Видеолекция",
        durationLabel: "3 минуты",
        title: "Почему важно ходить к врачу",
        image: "/images/education-card/2.webp",
        imageClass: "education-card__image--girl",
        imageWidth: "470",
        imageHeight: "664",
        href: "#",
        ctaLabel: "Открыть тему «Почему важно ходить к врачу»",
      },
      {
        typeLabel: "Видеолекция",
        durationLabel: "3 минуты",
        title: "Полезные привычки каждый день",
        image: "/images/education-card/1.webp",
        imageClass: "education-card__image--brush",
        imageWidth: "1082",
        imageHeight: "1082",
        href: "#",
        ctaLabel: "Открыть тему «Полезные привычки каждый день»",
      },
      {
        typeLabel: "Видеолекция",
        durationLabel: "3 минуты",
        title: "Зубки любят чистоту",
        image: "/images/education-card/2.webp",
        imageClass: "education-card__image--girl",
        imageWidth: "470",
        imageHeight: "664",
        href: "#",
        ctaLabel: "Открыть тему «Зубки любят чистоту»",
      },
    ],
  },
};
