export default {
  "/quiz-start.html": {
    title: "Квиз про зубки",
    quizPageTitle: "Квиз про зубки",
    quizBackHref: "/index.html",
    quizBackText: "Назад",
    quizStartTitle: "12 простых вопросов",
    quizStartDescription:
      "Ответьте на вопросы на темы изученных статей из прошлых уроков и закрепите свои знания",
    quizLeaderboardHref: "/quiz-leaderboard.html",
    quizLeaderboardText: "Таблица лидеров",
    quizStartHref: "/quiz.html",
    quizStartButtonText: "Пройти квиз",
  },
  "/quiz.html": {
    title: "Квиз про зубки",
    quizPageTitle: "Квиз про зубки",
    quizBackHref: "/quiz-start.html",
    quizBackText: "Назад",
    quizCurrentQuestion: "1",
    quizTotalQuestions: "12",
    quizTimer: "1:44",
    quizQuestionText:
      "Какая концентрация фторидов (ppm) в зубной пасте считается оптимальной для подростков старше 12 лет?",
    quizPrevHref: "/quiz-start.html",
    quizPrevDisabled: true,
    quizNextHref: "#",
    quizOptions: [
      { value: "500", label: "500 ppm" },
      { value: "1000", label: "1000 ppm" },
      { value: "1450-1500", label: "1450–1500 ppm" },
      { value: "2500", label: "2500 ppm" },
    ],
  },
  "/quiz-images.html": {
    title: "Квиз про зубки",
    quizPageTitle: "Квиз про зубки",
    quizBackHref: "/quiz-start.html",
    quizBackText: "Назад",
    quizOptionsAsCards: true,
    quizCurrentQuestion: "2",
    quizTotalQuestions: "12",
    quizTimer: "1:35",
    quizQuestionText: "Выберите с чего правильно начинать чистить зубки.",
    quizPrevHref: "/quiz-start.html",
    quizNextHref: "#",
    quizOptions: [
      {
        value: "option-1",
        label: "Вариант ответа №1",
        image: "/images/quiz-option-cards/1.webp",
      },
      {
        value: "option-2",
        label: "Вариант ответа №2",
        image: "/images/quiz-option-cards/2.webp",
      },
      {
        value: "option-3",
        label: "Вариант ответа №2",
        image: "/images/quiz-option-cards/1.webp",
      },
    ],
  },
  "/quiz-completion.html": {
    title: "Квиз про зубки",
    quizPageTitle: "Квиз про зубки",
    quizBackHref: "/quiz-images.html",
    quizBackText: "Назад",
    quizCompletionTitle: "Вы молодец!",
    quizCompletionDescription:
      "Эти знания будут вам полезны в жизни и помогут сохранить ваши зубки здоровыми",
    quizCompletionStats: [
      { text: "11 правильных ответов" },
      { text: "за 1:44" },
    ],
    quizLeaderboardHref: "/quiz-leaderboard.html",
    quizLeaderboardText: "Таблица лидеров",
  },
  "/quiz-leaderboard.html": {
    title: "Таблица лидеров",
    quizPageTitle: "Квиз про зубки",
    quizBackHref: "/quiz-start.html",
    quizBackText: "Назад",
    quizLeaderboardInnerBackHref: "/quiz-start.html",
    quizLeaderboardHeading: "Таблица лидеров",
    quizLeaderboardEntries: [
      { place: "1", name: "Петров Ярослав", isFirst: true },
      { place: "2", name: "Яковлев Александр" },
      { place: "3", name: "Александров Сергей" },
      { place: "4", name: "Патрушев Егор" },
      { place: "5", name: "Филатова Яна" },
      { place: "6", name: "Вы", isCurrentUser: true },
      { place: "7", name: "Петренко Яков" },
      { place: "8", name: "Дмитриенко Иван" },
      { place: "9", name: "Дмитриенко Иван" },
      { place: "10", name: "Дмитриенко Иван" },
      { place: "11", name: "Ермакова Валерия" },
      { place: "12", name: "Смирнов Тимур" },
    ],
  },
};
